apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chiara-react-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chiarasei/chiara-react-app
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: chiara-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
