{
 "title": "Chiara App Service Dashboard",
 "description": "Monitors CPU, memory, pod status, and overall health of the Chiara App running in Kubernetes. Built using Prometheus metrics and visualized in Grafana for real-time observability.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": " Memory Usage (Chiara App)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"chiara-app\", container!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (Chiara App)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"chiara-app\", container!=\"\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"chiara-app\", phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"chiara-app\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}