replicaCount: 2

image:
  repository: ghcr.io/chiarasei/chiara-react-app
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
  host: chiaraaiconsulting.se
  hostWWW: www.chiaraaiconsulting.se
  tlsSecret: chiara-tls-secret
  certIssuer: letsencrypt-prod
  host: chiaraaiconsulting.se
  hostWWW: www.chiaraaiconsulting.se
  tlsSecret: chiara-tls-secret
  certIssuer: letsencrypt-prod